### ISSUE TITLE
Build failed! (node:40607) UnhandledPromiseRejectionWarning: Error: Cannot get cli tools directory path

### ISSUE THREAD

**Issue by Allan-Nava** [interfaced/zombiebox-platform-webos#1]
I got this error:

`npx zombiebox build webos
Extension about loaded
Extension cutejs loaded
Extension dependency-injection loaded
Extension ui loaded
Platform lg loaded
Platform pc loaded
Platform tizen loaded
Platform webos loaded
Compile app for webos platform in /Users/ies/Desktop/work/sportube/es-tv/dist/1.0.0/webos
PreBuild for webos in /Users/ies/Desktop/work/sportube/es-tv/dist/1.0.0/webos
Error: Cannot get cli tools directory path. Check README for possible solution
    at getToolsDir (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox-platform-webos/index.js:322:9)
    at PlatformWebOS.buildApp (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox-platform-webos/index.js:69:20)
    at runExternalScript (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox/lib/application.js:391:14)
    at module.exports (/Users/ies/Desktop/work/sportube/es-tv/prebuild.js:12:2)
    at runExternalScript (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox/lib/application.js:352:6)
    at buildPlatform (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox/lib/application.js:376:61)
    at buildFirstPlatform (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox/lib/application.js:413:5)
    at buildPlatforms (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox/lib/application.js:420:4)
    at Application.compile (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox/lib/application.js:468:3)
    at _application.ready.then (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox/bin/cli.js:87:34)
Build failed!
(node:40607) UnhandledPromiseRejectionWarning: Error: Cannot get cli tools directory path. Check README for possible solution
    at getToolsDir (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox-platform-webos/index.js:322:9)
    at PlatformWebOS.buildApp (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox-platform-webos/index.js:69:20)
    at runExternalScript (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox/lib/application.js:391:14)
    at module.exports (/Users/ies/Desktop/work/sportube/es-tv/prebuild.js:12:2)
    at runExternalScript (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox/lib/application.js:352:6)
    at buildPlatform (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox/lib/application.js:376:61)
    at buildFirstPlatform (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox/lib/application.js:413:5)
    at buildPlatforms (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox/lib/application.js:420:4)
    at Application.compile (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox/lib/application.js:468:3)
    at _application.ready.then (/Users/ies/Desktop/work/sportube/es-tv/node_modules/zombiebox/bin/cli.js:87:34)
(node:40607) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:40607) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by l1bbcsg** [comment]
The relevant error is: 
> Error: Cannot get cli tools directory path. Check README for possible solution

I believe the build script cannot find webos CLI executables. Are they installed? They should be and should also be either accessible from global PATH or through directory set in `toolsDir` config option.
See DOCS.md for details.

**Comment by Allan-Nava** [comment]
> The relevant error is:
> 
> > Error: Cannot get cli tools directory path. Check README for possible solution
> 
> I believe the build script cannot find webos CLI executables. Are they installed? They should be and should also be either accessible from global PATH or through directory set in `toolsDir` config option.
> See DOCS.md for details.

So i have to follow this doc -> https://github.com/interfaced/zombiebox-platform-webos/blob/master/DOCS.md
